version: '3.8'

services:
  mysql_db:
    image: mysql
    restart: 'always'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_persistence:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_persistence: